---
abstract: 'Search file contents in code repositories or other places'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  File::Spec: 0
  Test::More: 0
  Test::Warnings: 0.016
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-CodeSearch
provides:
  File::CodeSearch:
    file: lib/File/CodeSearch.pm
    version: v0.7.0
  File::CodeSearch::Highlighter:
    file: lib/File/CodeSearch/Highlighter.pm
    version: v0.7.0
  File::CodeSearch::RegexBuilder:
    file: lib/File/CodeSearch/RegexBuilder.pm
    version: v0.5.6
  File::CodeSearch::Replacer:
    file: lib/File/CodeSearch/Replacer.pm
    version: v0.7.0
requires:
  Carp: 0
  Clone: 0
  Config::General: 0
  File::Basename: 0
  File::Slurp: 0
  File::Spec: 0
  File::TypeCategories: 0.01
  File::chdir: 0
  IO::Handle: 0
  IO::Prompt: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 0
  Path::Tiny: 0.005
  Pod::Usage: 0
  Readonly: 0
  Scalar::Util: 0
  Term::ANSIColor: 0
  Term::Size::Any: 0
  autodie: 0
  perl: 5.006
  version: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=File-CodeSearch
  license: http://dev.perl.org/licenses/
  repository: http://github.com/ivanwills/File-CodeSearch
version: v0.7.0
